// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnSJVHioItNsc2kedyZTxJ7PvfX2hQC7Q',
    appId: '1:65231955877:web:aab053b6882e9894bdaa4c',
    messagingSenderId: '65231955877',
    projectId: 'bitesofsouth-a38f4',
    authDomain: 'bitesofsouth-a38f4.firebaseapp.com',
    storageBucket: 'bitesofsouth-a38f4.firebasestorage.app',
    measurementId: 'G-R9WE265DPN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpPMpAF7VbibnTYC7SxJ8VRX9BEGJl2AU',
    appId: '1:65231955877:android:f37a7e1822d0a2dbbdaa4c',
    messagingSenderId: '65231955877',
    projectId: 'bitesofsouth-a38f4',
    storageBucket: 'bitesofsouth-a38f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmr04g6F9oAbeibMsX_WkOvY__EjGRf4Y',
    appId: '1:65231955877:ios:6ac5c05503735848bdaa4c',
    messagingSenderId: '65231955877',
    projectId: 'bitesofsouth-a38f4',
    storageBucket: 'bitesofsouth-a38f4.firebasestorage.app',
    iosBundleId: 'com.example.bitesOfSouth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmr04g6F9oAbeibMsX_WkOvY__EjGRf4Y',
    appId: '1:65231955877:ios:6ac5c05503735848bdaa4c',
    messagingSenderId: '65231955877',
    projectId: 'bitesofsouth-a38f4',
    storageBucket: 'bitesofsouth-a38f4.firebasestorage.app',
    iosBundleId: 'com.example.bitesOfSouth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnSJVHioItNsc2kedyZTxJ7PvfX2hQC7Q',
    appId: '1:65231955877:web:4818d09baf185c08bdaa4c',
    messagingSenderId: '65231955877',
    projectId: 'bitesofsouth-a38f4',
    authDomain: 'bitesofsouth-a38f4.firebaseapp.com',
    storageBucket: 'bitesofsouth-a38f4.firebasestorage.app',
    measurementId: 'G-PSLDPGX2Q5',
  );
}
